apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: awstargetgroups.aws.k8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/enhancements/pull/1111"
spec:
  group: aws.k8s.io
  names:
    kind: AWSTargetGroup
    listKind: AWSTargetGroupList
    plural: awstargetgroups
    singular: awstargetgroup
    shortNames:
      - atg
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetType:
                  type: string
                  enum: ["instance", "ip"]
                port:
                  type: integer
                  minimum: 1
                  maximum: 65535
                protocol:
                  type: string
                  enum: ["HTTP", "HTTPS", "TCP"]
                vpcId:
                  type: string
                region:
                  type: string
                  description: "AWS region where the target group should be created"

                serviceRef:
                  type: object
                  properties:
                    name:
                      type: string
                    port:
                      type: integer
                      minimum: 1
                      maximum: 65535
                  required:
                    - name
                    - port
                loadBalancerRef:
                  type: object
                  properties:
                    name:
                      type: string
                      description: "Name of the load balancer"
                  required:
                    - name
              required:
                - targetType
                - port
                - protocol
                - vpcId
                - region
                - serviceRef
                - loadBalancerRef
            status:
              type: object
              properties:
                targetGroupArn:
                  type: string
                state:
                  type: string
                error:
                  type: string
                ruleArn:
                  type: string