apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awstargetgroup-webhook-cert
  namespace: default
spec:
  dnsNames:
  - awstargetgroup-webhook.default.svc
  - awstargetgroup-webhook.default.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
  secretName: webhook-tls
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}