apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: awstargetgroup-webhook
  annotations:
    cert-manager.io/inject-ca-from: default/awstargetgroup-webhook-cert
webhooks:
- name: awstargetgroup.aws.k8s.io
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
  failurePolicy: Fail
  clientConfig:
    service:
      name: awstargetgroup-webhook
      namespace: default
      path: "/mutate"
      port: 8443
  rules:
  - apiGroups: ["aws.k8s.io"]
    apiVersions: ["v1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["awstargetgroups"]
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values: ["kube-system"]